### ISSUE TITLE
Could Not Save Application Settings (0.6-BETA-2)

### ISSUE THREAD

**Issue by davidjgonzalez** [headwirecom/aem-ide-tooling-4-intellij#11]
Upgraded to 0.6-BETA-2 to day and noticed the intellij dialog popping up.

It *seems* to happen whenever I switch focus from Intellij to another application (intellij grabs focus back w the popup window)

![2015-08-22 at 9 33 am](https://cloud.githubusercontent.com/assets/1451868/9424193/fa9c3300-48b0-11e5-9431-c1d5c4469d0d.png)

**Comment by schaefa** [comment]
This is quite outdated and so I close it for now.
