### ISSUE TITLE
Indexing takes forever

### ISSUE THREAD

**Issue by alvinsgithub** [headwirecom/aem-ide-tooling-4-intellij#19]
Plugin Version 0.7.1
IntelliJ Version 14.1.7

With the plugin enabled, indexing would take forever and eventually stop responding. 
Invalidating the caches and restarting do not help. The only solution to make intelliJ working is to restart with the AEM plugin disabled.

**Comment by schaefa** [comment]
14.1.7 is a pretty old IntelliJ version. Can yo try with a newer version and see if it remains an issue?

**Comment by sammykumar** [comment]
Really would like to use this plugin but I'm also experiencing the same issue. In my indexing never finishes. I need use Task Manger to kill the process.

Plugin Version: 0.7.1
IntelliJ IDEA 2016.2.4
Build #IU-162.2032.8, built on September 9, 2016
JRE: 1.8.0_91-b15 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by SBPrakash** [comment]
@sammykumar same issue..Please help

**Comment by schaefa** [comment]
Do you guys see any indication in the AEM Console or IntelliJ logs on what is causing it?

**Comment by schaefa** [comment]
I see some deadlocks during loading a project but only in Debug mode.

Can you try the latest 0.7.2-beta build: https://db.tt/CaZfB5mj

**Comment by schaefa** [comment]
I was finally able to reproduce the issue where the automatic start of a Run / Debug Connection is ending up in a deadlock. For now I disabled that feature to make the plugin usable again until we have a fix for it. Please download 0.7.2-beta2 from here: https://db.tt/Q7a1KSlE

**Comment by schaefa** [comment]
There was a deadlock in the plugin but this is resolved now.

Please check out release 1.0 and see if you continue to see this issue.

**Comment by tduffey** [comment]
@schaefa having the same issue in plugin version 1.0.3.2 with IntelliJ 2017.3. Sometimes IntelliJ works, other times it hangs on startup and only way to make it work again is disable the plugin.
