### ISSUE TITLE
Java code Hot Swap problem with Java 8

### ISSUE THREAD

**Issue by chillinPanda** [headwirecom/aem-ide-tooling-4-intellij#20]
Hello,
- I have a project based on Java 8
- I want to use Hot Swap for Java code changes
- IntelliJ IDEA 2016.2.4
- Plugin version: 0.7.1
# Problem

When I do code changes and the build process runs, I get following error message:

```
Error:Felix SCR: [vwfs-vw-site-core] Unable to scan class files: package.class (Class file format probably not supported by ASM ?)
```

Googling resulted in this: http://stackoverflow.com/a/38945890

Seems like the Scr plugin for intelliJ is too old to read Java 8 classes.
# Workaround 1

I changed my source and target java version to 1.7 in my maven pom. After doing this, hot swap works.

But this is not good, since I want to stay with Java 8.
# Workaround 2

Deactivate `Felix SCR Annotation Processor` plugin. After doing this, hot swap works. But I don't know which side-effects I will introduce by this.

In your [documentation](https://github.com/headwirecom/aem-ide-tooling-4-intellij/blob/master/documenation/AEM%20Tooling%20Plugin%20for%20IntelliJ%20IDEA.md#31-maven-osgi-bundle-annotation-support) is written, that this plugin is needed for hot swap. But it works also without it.

**Comment by schaefa** [comment]
Thanks for reporting that. I am looking into that and see what needs to be done here.

For you info the Felix SCR Annotation Processor is adding necessary methods (bind / unbind XX) methods to the class. If you can such an annotation the hot swap will fail as the method signatures have changed. If not then you should be fine.

I don't like the dependency on another plugin but I don't want to just repeat what someone else did for just that. If there is an update coming out soon I will go with that otherwise need to look into other options.

**Comment by chillinPanda** [comment]
> If there is an update coming out soon I will go with that otherwise need to look into other options.

The [plugin page](https://plugins.jetbrains.com/plugin/7009?pr=) states, that the last version is from 04/28/2014

The [github project](https://github.com/chilicat/felix-annotation-processor) has very low and old activity. I don't think that there is comming a new version soon.

**Comment by schaefa** [comment]
Currently I have no time left to work on the plugin due to heavy workload. Maybe over Thanksgiving I can have a look into this.

**Comment by schaefa** [comment]
Even in release 1.0 we still have the dependency on the Felix SCR Annotation Plugin but there is a forked project that works with JDK 1.8:

https://github.com/bobi/felix-annotation-processor/releases

Please use their release 1.7 and you should be able to use Felix Annotations together with Hot Swap.

**Comment by debbiesrain** [comment]
Disabling the **Felix SCR annotation processor** plugin fixed it.  I installed this plugin for using the **aem-ide-tooling-4-intellij** from headwirecom.  It was working for quite a while until today suddenly giving me an issue in running my unit tests (needless to say, there were no changes made in my java, mvn versions or in my IDE). 

This plugin is really old (2014). I hope they will release a newer version soon.
