### ISSUE TITLE
Error while starting the aem server

### ISSUE THREAD

**Issue by XTIER-Tech** [headwirecom/aem-ide-tooling-4-intellij#48]
Hi,

I have added this IDE Plugin. But while starting AEM server. Its giving me an error during startup
`12:11:44 PM No Content Found: No Content (jcr_root folder) found for Module: 'myApp-content'. This is necessary for the Publishing of Content to Work.`
Its multimodule maven project.

![error](https://user-images.githubusercontent.com/28855190/27215298-25467230-528e-11e7-8847-a58711eb0200.png)

**Comment by schaefa** [comment]
Can you show my your project structure in myApp-content? The plugin tries to figure out where you content root is (jcr_root) and it cannot find it hence the error.
