### ISSUE TITLE
Synchronizing fails with error: unknown typeHint value = "String"

### ISSUE THREAD

**Issue by jackrus01** [headwirecom/aem-ide-tooling-4-intellij#49]
The error occurs when trying to synchronize ui.apps, it fails with the following stacktrace:
Unknown typeHint value 'String'
java.lang.IllegalArgumentException: Unknown typeHint value 'String'
	at org.apache.sling.ide.impl.vlt.serialization.ContentXmlHandler$TypeHint.parsePossiblyTypedValue(ContentXmlHandler.java:261)
	at org.apache.sling.ide.impl.vlt.serialization.ContentXmlHandler.startElement(ContentXmlHandler.java:69)

There's an enum in ContextXmlHandler called TypeHint, that contains a number of types except String.

**Comment by B3r** [comment]
I had the same problem and solved it.
AEM has some Property types like Boolean, (I think) Decimal, and some more. The default type is String.
So if you use fields like 
```
<title jcr:primaryType="nt:unstructured"
   fieldLabel="Some Label:"
   name="./jcr:title"
   emptyText="{String}Some text."
   sling:resourceType="granite/ui/components/foundation/form/textfield"
   required="{Boolean}true"
   maxlength="{Long}255"
/>
```
the properties "required" and "maxlength" will work, while emptyText will not. Just remove "{String}" and the error should disappear.

Hope I could help.
Greetz,
Marvin
