### ISSUE TITLE
Automatic installation of core bundle

### ISSUE THREAD

**Issue by boser87** [headwirecom/aem-ide-tooling-4-intellij#51]
Hi, 

I cannot understand if this plugin provides automatic installation every new build of bunldes. If so, I cannot make this feature work. The bundle is recognized by the plugin but everytime I save a Java file in a bundle (and then the build is run), the automatic deploy is not starting (nothing is printed in the log files, with debug mode switched on).

I am using version 1.0.1 of this plugin.

IntelliJ IDEA 2016.3.4
Build #IC-163.12024.16, built on January 31, 2017
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

AEM 6.3

The project bootstrap is done with Adobe Maven Archetype.

Thanks!

**Comment by schaefa** [comment]
This is not quite how it works. When a Java file of a bundle is changed and saved then it will be compiled and hot swapped into the server. In order to deploy the bundle needs to be deploy in the AEM tree.

**Comment by boser87** [comment]
Sorry, my bad. I misunderstood the way it is supposed to work. I was missing the most important part: the connection must be in debug mode to make the hot swap work. Thanks!
