### ISSUE TITLE
Debug error : Failed to handle Import

### ISSUE THREAD

**Issue by josephh** [headwirecom/aem-ide-tooling-4-intellij#52]
Running the plugin version 1.0.2 on intellij 2017.3; mac osx sierra 10.12.6.
Trying to import from a connected server the contents of src/main/content/jcr_root, seeing the debug error,
> 23:01:18 Debug Message: Import from Server failed because of Exception: 'com.headwire.aem.tooling.intellij.eclipse.stub.CoreException: Failed to handle Import'
Is this a problem with the plugin?

**Comment by schaefa** [comment]
Please try the release 1.0.3-beta as this has some fixes for Mac OS X Sierra. Let me know if the problem persists.

**Comment by josephh** [comment]
hi @schaefa 
sorry not to update you on this sooner.  I've been trying the plugin again today with similar failures as in January (and I note #56 is reporting similar).

## My current setup
Mac high sierra 10.13.3.
Intellij 2017.3.5 (build March 5 2018)
AEM Tooling v1.0.3.2

## Usage - import
1. I deploy my app to a local aem instance via Maven
1. in Intellij connect to my local server in debug mode
1. highlight in the code project window my 'components' project src/main/content/jcr_root folder and right-click `aem > import-from` 

Import  fails with,
```17:32:40 Debug Message: Import from Server failed because of Exception: 'com.headwire.aem.tooling.intellij.eclipse.stub.CoreException: Failed to handle Import'``` 

## Usage - deploy
1. Attempt to 'force deploy' the application with the tooling 

Deploy doesn't appear to change the deployed application apps/ contents.

## Observations
I thought this was likely to be something to do with my code project - which has been largely authored by another team - so i've tried similar with an AEM project created using lazybones and the instructions [here](https://helpx.adobe.com/experience-manager/using/aem_lazybones.html)).
If i click on jcr_content in the lazybones project i get `Failed to handle Import` but clicking on a sub-folder - e.g. components, results in successful import and I can add more components (using crx/de) and do this repeatedly with success.  I wondered if i was misusing the tool so went back to my own project but clicking on sub-folders and trying `import-from` fails repeatedly.

I note the debug output mentions multiple content base paths - is this OK?

Some  debug output from my 'foo' project
```28/03/2018
23:28	Debug Message: Folder Path: 'com.headwire.aem.tooling.intellij.eclipse.stub.IPath@4018e2c8'
23:28	Debug Message: OS Based String: '/Users/joe/AEM6/aem/foo-components/src/main/content/jcr_root
23:28	Debug Message: Import from Server failed because of Exception: 'com.headwire.aem.tooling.intellij.eclipse.stub.CoreException: Failed to handle Import
23:28	Start Action: 'Import from Server
23:28	Debug Message: Content Base Path: '/Users/joe/AEM6/aem/foo-content/src/main/content/META-INF
23:28	Debug Message: Content Base Path: '/Users/joe/AEM6/aem/foo-content/src/main/content/jcr_root
23:28	Debug Message: Content Base Path: '/Users/joe/AEM6/aem/foo-components/src/main/content/META-INF
23:28	Debug Message: Content Base Path: '/Users/joe/AEM6/aem/foo-components/../foo-fe/node_modules/@foo/component-library/dist
23:28	Debug Message: Content Base Path: '/Users/joe/AEM6/aem/foo-components/src/main/content/jcr_root

23:28	Successfully ended Action: 'Import from Server'

```

**Comment by schaefa** [comment]
Hi

Thanks for the update. The Core Exception is an exception from the underlying API trying to access or transfer the data from the server.

Can you please attache the IntelliJ Log file as this should give me information especially the stack trace of the Core Exception. IntelliJ has a menu entry like 'Show Log in ...'.

Thanks - Andreas
