### ISSUE TITLE
No Content Folder Configuration found

### ISSUE THREAD

**Issue by GonzaloCalandria** [headwirecom/aem-ide-tooling-4-intellij#53]
I'm receiving this message in one of my packages, what this means? 
It needs to be a `.content.xml` in the apps folder??
![image](https://user-images.githubusercontent.com/2286280/34881546-9e403c3a-f792-11e7-9097-89673176c55c.png)

**Comment by schaefa** [comment]
I think it means that /apps is not part of a filter entry (META-INF/vault/filter.xml) and it does not exist on the remote server.

Can you post your filter.xml file?

**Comment by GonzaloCalandria** [comment]
This is my filter.xml
```
<?xml version="1.0" encoding="UTF-8"?>

<workspaceFilter version="1.0">
    <filter root="/apps"/>
    <filter root="/etc"/>
</workspaceFilter>
```
Now the error is gone, I've simplified the filter.xml BUT now I've another error when I try to deploy the code:
`Deploy Module Failed: Deploy Module: 'my-application' failed due to OSGi Client Exception: 'org.apache.sling.ide.io.ConnectorException: /etc/workflow/models/my-app/my-content-publish/jcr:content/model'`
That model is an xml file of the workflow, what could be wrong here?

**Comment by schaefa** [comment]
I would be careful with that setup. This means that you remove everything from /apps and /etc that is not in your project.

Anyhow to go ahead here I need to have the exception stacktrace and a directory structure to see if there is something weird with your setup.
