### ISSUE TITLE
'Import from' does not work

### ISSUE THREAD

**Issue by vixenaga** [headwirecom/aem-ide-tooling-4-intellij#56]
Hi,
I am using plugin version 1.0.3.2, Intellij ulimate edition 2017.1.4 and AEM 6.3. I work on Windows. I am trying to import some components, I get this message:
Successfully ended Action 'Import from Server'
components don't get imported though.
I just started using this plugin, is there something I should do before using?
Agnieszka

**Comment by schaefa** [comment]
Can you provide some more details?

What is the node you select to import, are you connected to AEM and can you provide part of the IntelliJ logs that covers the import. Some screenshots would be helpful.

**Comment by josephh** [comment]
HI @schaefa I couldn't get 'import from...' to work as you know a while ago.  (I had problems using AEM plugins for Eclipse IDE but was able to resolve those by renaming _cq_dialog.xml to prefer a _cq_dialog folder containing .content.xml files).

I'd rather use Intellij, given the choice so tried AEM tools for Intellij again today.  On creating a new server and trying the 'AEM > import from...' option the import successfully works, but not subsequently. 

I'll attach my log files from today 🤞

**Comment by schaefa** [comment]
@josephh I reviewed your logs and I found this:

Import failed: 'Resource at path /apps/simplyhealth/components/page/editorialpage/editorialpage.html is not a direct child of /apps/simplyhealth/components/page/editorialpage/basic' 
java.lang.IllegalArgumentException: Resource at path /apps/simplyhealth/components/page/editorialpage/editorialpage.html is not a direct child of /apps/simplyhealth/components/page/editorialpage/basic

I am not sure what is going on but I am assume that you have a new entry (editorialpage) in the parent node which is missing in IntelliJ.

Can you try to import from /apps/simplyhealth/components/page/editorialpage and let me know what happened there (go to the idea.log and search for 'Import failed:'.

Thanks - Andy Schaefer

**Comment by vijknair** [comment]
All, 'Import From' doesn't work for me, I am trying with the latest Beta drop on Mac OS Sera , IntelliJ 2018.1, PFB the trace.

`4:09 PM	Debug Message: Folder Path: 'com.headwire.aem.tooling.intellij.eclipse.stub.IPath@243a85cf'

4:09 PM	Debug Message: OS Based String: '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps/fmdita'

4:09 PM	Debug Message: Folder Path: 'com.headwire.aem.tooling.intellij.eclipse.stub.IPath@74b5f96d'

4:09 PM	Debug Message: OS Based String: '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps/fmdita/vijesh-fixed-import'

4:09 PM	Start Action: 'Import from Server'

4:09 PM	Debug Message: Content Base Path: '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root'

4:09 PM	Debug Message: Content Base Path: '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root'

4:09 PM	Updated File: Start to Updated File '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps/fmdita/vijesh-fixed-import' with Change Type: CREATED

4:09 PM	Debug Message: Got Repository: 'org.apache.sling.ide.impl.vlt.VltRepository@2dede1fc'

4:09 PM	Debug Message: Got Command: 'org.apache.sling.ide.transport.TracingCommand@1486119'

4:09 PM	Debug Message: Check Parent File: File Wrapper for: /Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps/fmdita

4:09 PM	Debug Message: Check Parent File: File Wrapper for: /Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps

4:09 PM	Debug Message: Check Parent File: File Wrapper for: /Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root

4:09 PM	Successfully ended Action: 'Import from Server'

4:09 PM	Updated File: Successfully Updated File '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps/fmdita/vijesh-fixed-import'

4:09 PM	Debug Message: Content Base Path: '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root'

4:09 PM	Updated File: Start to Updated File '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps/fmdita/vijesh-fixed-import/.content.xml' with Change Type: CREATED

4:09 PM	Debug Message: Got Repository: 'org.apache.sling.ide.impl.vlt.VltRepository@2dede1fc'

4:09 PM	Debug Message: Got Command: 'null'

4:09 PM	Updated File: Failed to Update File '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps/fmdita/vijesh-fixed-import/.content.xml' in Module 'Module: module name = 'pwc-madison.ui.apps', last modification timestamp = 0, part of build = true'

4:09 PM	Updated File: Start to Updated File '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps/fmdita/vijesh-fixed-import/.content.xml' with Change Type: CHANGED

4:09 PM	Debug Message: Got Repository: 'org.apache.sling.ide.impl.vlt.VltRepository@2dede1fc'

4:09 PM	Debug Message: Got Command: 'null'

4:09 PM	Updated File: Failed to Update File '/Users/vijeshknair/Documents/sourcecode/pwc.madison.base/ui.apps/src/main/content/jcr_root/apps/fmdita/vijesh-fixed-import/.content.xml' in Module 'Module: module name = 'pwc-madison.ui.apps', last modification timestamp = 0, part of build = true'`

**Comment by schaefa** [comment]
I tested the 'Import from Server' and it works for me with the caveat that when a node properties were updated then I had to call the 'Import from Server' on the node and not on .content.xml.

**Comment by schaefa** [comment]
Due to high maintenance we decided to End the Development of this plugin.
