### ISSUE TITLE
Could not initialize class com.headwire.aemdc.gui.MainApp

### ISSUE THREAD

**Issue by sammyza** [headwirecom/aem-ide-tooling-4-intellij#58]
I am getting this issue straight after I installed the plugin on IntelliJ(2018.1.5 Ultimate Edition - Build 181.5281.24)

Not sure why but I need help on setting up the plugin

**Comment by schaefa** [comment]
To get started I would need the following:

1) Which version of the plugin and where did you get it from?
2) What is the exception you see (both in the UI as well as in the IntelliJ log)?
3) Which version your are using for OS and Java (if you run it w/o the bundle JDK of IntelliJ)?

Thanks for your help - Andy Schaefer
