### ISSUE TITLE
Context path config doesnt seem to work

### ISSUE THREAD

**Issue by davidjgonzalez** [headwirecom/aem-ide-tooling-4-intellij#6]
Im fixing some Context Paths in AEM Tools, and restarted AEM under /aem/... I cant get the plugin to work; i went into the plugin config and set Context Path to "/aem" .. i even "cleared" the config (including the lightning bolt) and tried to re-establish but get these errors..

```
12:28:31 PM Cannot Connect to Repository: Cannot Connect to Repository with Name 'Localhost Author' because connection was refused
12:28:54 PM Start Connection to Sling Repository: Start Connection to Remote Sling Repository
12:28:54 PM Start Connection to Sling Repository: Start Connection to Remote Sling Repository
```

**Comment by zerovirus23** [comment]
Hey guys, do you know if this issue is still happening? Today I got that error trying to deploy from Intellij to AEM 6.0.

**Comment by schaefa** [comment]
Yes, as far as I know this is still not fixed. I will have a look into this again soon but this is part of the Jackrabbit WebDav connector and there is not much I can do about it.

**Comment by schaefa** [comment]
Due to high maintenance we decided to End the Development of this plugin.
