### ISSUE TITLE
Unable to open folder or new project after install Mac 10.13.6 (High Sierra)

### ISSUE THREAD

**Issue by smcauliffe** [headwirecom/aem-ide-tooling-4-intellij#60]
**Describe the bug**
After installing plugin through IntelliJ preferences (Community 2018.2) and restarting, IntelliJ is unable to load any existing project, folder, or newly created Empty Project.

**To Reproduce**
1. Install Plugin using IntelliJ Community 2018.2
2. Restart
3. On open of a project, aemdc-files folder is written to ~/Library/Application Support/IdeaIC2018.2
4. IntelliJ hangs, project never loads, fan goes nuts

**Expected behavior**
Expected project to at least open and plugin to potentially work.

**Desktop (please complete the following information):**
 - OS: Mac 10.13.6 High Sierra
 - Java: java -version reports java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
 - IntelliJ: 2018.2 Community
 - Plugin: aem-ide-tooling-4-intellij from IntelliJ repo

**Comment by schaefa** [comment]
Hi

Sorry to hear that.

Which version of the IntelliJ plugin are you using? Please get that info from the Preferences/Plugins page as the plugin info page might not show all the minor updates.

If you are not using 1.0.3.4-beta2 the please go to our plugin releases here:
https://github.com/headwirecom/aem-ide-tooling-4-intellij/releases
Download it and install it through the Preferences/Plugins 'Install plugin from disk...'.

**Comment by schaefa** [comment]
Due to high maintenance we decided to End the Development of this plugin.
