### ISSUE TITLE
Unable to import JCR properties from .content.xml

### ISSUE THREAD

**Issue by aadams26** [headwirecom/aem-ide-tooling-4-intellij#62]
AEM Tooling `import` functionality is not importing JCR properties.

**To Reproduce**
1. Log into AEM instance
2. Go to CRXDE Lite
3. Create a new node
4. Go to IntelliJ IDEA
5. Import the newly created node from it's parent
6. Review the `.content.xml`

**Note that the .content.xml only contains the jcr:root and does not contain properties of that node:**
```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root />
```

**Expected behavior**
The `.content.xml` file should reflect all properties assigned to it under the CRXDE.
E.g.
```
<?xml version="1.0" encoding="UTF-8"?>
<jcr:root xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:jcr="http://www.jcp.org/jcr/1.0"
    jcr:primaryType="cq:ClientLibraryFolder"
    categories="[project-name.components]"/>
```

**Additional info:**
 - OS: Windows 10
 - Java: 1.8
 - IntelliJ Ultimate v2018.2.6
 - Plugin v1.0.3.4

**Comment by HanSolo80** [comment]
I have the same issue. Not only does the "Import from" functionality not work for any properties and sub nodes underneath root. It also doesn't update the CRX structure when server connection is running and you change the .content.xml file in the IDE.

**Comment by schaefa** [comment]
I'll check it out

**Comment by schaefa** [comment]
On the release 1.0.3.5-beta the import works with the caveat that one has to call 'Import form Server' on the node and not on .content.xml.

Let me know if this is still an issue.

**Comment by schaefa** [comment]
Due to high maintenance we decided to End the Development of this plugin.
