### ISSUE TITLE
Code hot swap not working anymore

### ISSUE THREAD

**Issue by macinos** [headwirecom/aem-ide-tooling-4-intellij#64]
The **hot swap process** is not working for our team anymore, since we started using IDEA 2019.x. The configuration of all plugins, server and dependencies is the same.

Debugging itself and deploying of changes in JSP files is working well.

After modifying a body of some java method and saving, the recompilation and Felix SCR process starts as usual, but it doesn´t end with the the hot swap or any kind of other info except that the build completed successfully.

**Versions**
- Windows 7 & 10
- JDK 1.8.0_92
- IDEA 2019.2 and 2019.1
- AEM Tooling - 1.0.3.2
- Felix SCR Annotation Processor 1.6.2 from marketplace https://plugins.jetbrains.com/plugin/7009-felix-scr-annotation-processor/

**Comment by schaefa** [comment]
I will have a look into this. If you find time let me know if that is still an issue with 1.0.3.5-beta

**Comment by macinos** [comment]
Hello Andreas,
Thank You for the response. I installed the beta manually from the releases section. JSP file vault update still seems to work properly, however the hot swap seems to encounter a new error for me now:

![image](https://user-images.githubusercontent.com/9002361/71668477-5ccd5d00-2d69-11ea-95d4-2635a58e1de7.png)

The Felix SCR processor is still on version 1.6.2, is that ok? It is configured like this:

![image](https://user-images.githubusercontent.com/9002361/71668538-969e6380-2d69-11ea-8df7-d33dd5984ac0.png)

**Comment by schaefa** [comment]
Due to high maintenance we decided to End the Development of this plugin.
